CC = gcc
CFLAGS = -pipe -ggdb -Wall -Wextra -Wno-unused-parameter -ansi -pedantic
LDFLAGS = -framework OpenGL -framework GLUT

OBJS=hanoi.o stack.o objects.o main.o

hanoigl: $(OBJS)
	gcc $(LDFLAGS) $(OBJS) -o hanoigl

.PHONY clean:
	rm -f *.o hanoigl
